using ERP_API.Data;
using ERP_API.Dtos;
using ERP_API.Interfaces;
using ERP_API.Models;
using Microsoft.EntityFrameworkCore;

namespace ERP_API.Services;

/// <summary>
/// EF Core-backed implementation of <see cref="IInquiryService"/>. Mirrors the
/// behaviour of the frontend inquiry.service.js: sequential inquiry numbers,
/// item normalisation, and created/updated timestamps.
/// </summary>
public class InquiryService : IInquiryService
{
    private readonly ErpDbContext _db;

    public InquiryService(ErpDbContext db) => _db = db;

    public async Task<List<Inquiry>> GetAllAsync()
    {
        // Newest first, matching the frontend's byNewestFirst sort.
        return await _db.Inquiries
            .Include(i => i.Items)
                .ThenInclude(item => item.RawMaterials)
            .OrderByDescending(i => i.CreatedAt)
            .ToListAsync();
    }

    public async Task<Inquiry?> GetByIdAsync(int id)
    {
        return await _db.Inquiries
            .Include(i => i.Items)
                .ThenInclude(item => item.RawMaterials)
            .FirstOrDefaultAsync(i => i.Id == id);
    }

    public async Task<Inquiry> CreateAsync(InquiryRequest draft)
    {
        var now = DateTime.UtcNow.ToString("o");
        var record = new Inquiry
        {
            // Id is auto-generated by the database (auto-increment).
            InquiryNo = await NextInquiryNoAsync(),
            CustomerName = (draft.CustomerName ?? string.Empty).Trim(),
            CustomerContact = draft.CustomerContact?.Trim(),
            InquiryDate = draft.InquiryDate,
            Status = string.IsNullOrWhiteSpace(draft.Status) ? "draft" : draft.Status,
            Notes = draft.Notes?.Trim(),
            Items = NormaliseItems(draft.Items),
            CreatedBy = "Operations User",
            CreatedAt = now,
            UpdatedAt = now,
        };

        _db.Inquiries.Add(record);
        await _db.SaveChangesAsync();
        return record;
    }

    public async Task<Inquiry?> UpdateAsync(int id, InquiryRequest draft)
    {
        var existing = await _db.Inquiries
            .Include(i => i.Items)
                .ThenInclude(item => item.RawMaterials)
            .FirstOrDefaultAsync(i => i.Id == id);
        if (existing is null) return null;

        existing.CustomerName = (draft.CustomerName ?? string.Empty).Trim();
        existing.CustomerContact = draft.CustomerContact?.Trim();
        existing.InquiryDate = draft.InquiryDate;
        existing.Status = string.IsNullOrWhiteSpace(draft.Status) ? existing.Status : draft.Status;
        existing.Notes = draft.Notes?.Trim();
        existing.UpdatedAt = DateTime.UtcNow.ToString("o");

        // Replace the line items wholesale (cascade delete removes the old rows).
        _db.InquiryItems.RemoveRange(existing.Items);
        existing.Items = NormaliseItems(draft.Items);

        await _db.SaveChangesAsync();
        return existing;
    }

    public async Task<bool> DeleteAsync(int id)
    {
        var existing = await _db.Inquiries.FirstOrDefaultAsync(i => i.Id == id);
        if (existing is null) return false;

        _db.Inquiries.Remove(existing);
        await _db.SaveChangesAsync();
        return true;
    }

    public async Task<Inquiry?> SetStatusAsync(int id, string status)
    {
        var existing = await _db.Inquiries.FirstOrDefaultAsync(i => i.Id == id);
        if (existing is null) return null;

        existing.Status = status;
        existing.UpdatedAt = DateTime.UtcNow.ToString("o");
        await _db.SaveChangesAsync();
        return existing;
    }

    /// <summary>Generates the next sequential inquiry number, e.g. INQ-2026-0004.</summary>
    private async Task<string> NextInquiryNoAsync()
    {
        var year = DateTime.UtcNow.Year;
        var prefix = $"INQ-{year}-";

        var maxSeq = 0;
        var numbers = await _db.Inquiries
            .Where(i => i.InquiryNo.StartsWith(prefix))
            .Select(i => i.InquiryNo)
            .ToListAsync();

        foreach (var no in numbers)
        {
            if (int.TryParse(no[prefix.Length..], out var seq))
                maxSeq = Math.Max(maxSeq, seq);
        }

        return $"{prefix}{(maxSeq + 1):D4}";
    }

    /// <summary>
    /// Maps incoming request rows into entities: strings trimmed, empty material
    /// rows dropped. Ids are left unset so the database auto-generates them.
    /// Mirrors the frontend normaliseItems().
    /// </summary>
    private static List<InquiryItem> NormaliseItems(List<InquiryItemRequest>? items)
    {
        items ??= new List<InquiryItemRequest>();
        return items.Select(item => new InquiryItem
        {
            ProductName = (item.ProductName ?? string.Empty).Trim(),
            ProductCode = item.ProductCode?.Trim(),
            Quantity = item.Quantity,
            Unit = string.IsNullOrWhiteSpace(item.Unit) ? "pcs" : item.Unit,
            TargetDeliveryDate = item.TargetDeliveryDate ?? string.Empty,
            Remarks = item.Remarks?.Trim(),
            RawMaterials = (item.RawMaterials ?? new List<RawMaterialRequest>())
                .Where(m => !string.IsNullOrWhiteSpace(m.MaterialName))
                .Select(m => new RawMaterialRequirement
                {
                    MaterialName = m.MaterialName.Trim(),
                    Quantity = m.Quantity,
                    Unit = string.IsNullOrWhiteSpace(m.Unit) ? "kg" : m.Unit,
                    Notes = m.Notes?.Trim(),
                })
                .ToList(),
        }).ToList();
    }
}
