using ERP_API.Data;
using ERP_API.Dtos;
using ERP_API.Interfaces;
using ERP_API.Models;
using Microsoft.EntityFrameworkCore;

namespace ERP_API.Services;

/// <summary>
/// EF Core-backed implementation of <see cref="IProcurementService"/>. Mirrors the
/// frontend procurement.service.js: sequential PO numbers (PO-2026-NNNN), item
/// normalisation, status derived from received quantities, and the receive flow.
/// </summary>
public class ProcurementService : IProcurementService
{
    private readonly ErpDbContext _db;

    public ProcurementService(ErpDbContext db) => _db = db;

    public async Task<List<PurchaseOrder>> GetAllAsync()
    {
        return await _db.PurchaseOrders
            .Include(p => p.Items)
            .OrderByDescending(p => p.CreatedAt)
            .ToListAsync();
    }

    public async Task<PurchaseOrder?> GetByIdAsync(int id)
    {
        return await _db.PurchaseOrders
            .Include(p => p.Items)
            .FirstOrDefaultAsync(p => p.Id == id);
    }

    public async Task<PurchaseOrder> CreateAsync(PurchaseOrderRequest draft)
    {
        var now = DateTime.UtcNow.ToString("o");
        var record = new PurchaseOrder
        {
            // Id is auto-generated by the database (auto-increment).
            PoNo = await NextPoNoAsync(),
            SupplierName = (draft.SupplierName ?? string.Empty).Trim(),
            SupplierContact = draft.SupplierContact?.Trim(),
            Status = string.IsNullOrWhiteSpace(draft.Status) ? "draft" : draft.Status,
            OrderDate = draft.OrderDate,
            ExpectedDate = draft.ExpectedDate,
            SourceInquiryId = draft.SourceInquiryId,
            SourceInquiryNo = draft.SourceInquiryNo,
            Notes = draft.Notes?.Trim(),
            Items = NormaliseItems(draft.Items),
            CreatedBy = "Operations User",
            CreatedAt = now,
            UpdatedAt = now,
        };

        _db.PurchaseOrders.Add(record);
        await _db.SaveChangesAsync();
        return record;
    }

    public async Task<PurchaseOrder?> UpdateAsync(int id, PurchaseOrderRequest draft)
    {
        var existing = await _db.PurchaseOrders
            .Include(p => p.Items)
            .FirstOrDefaultAsync(p => p.Id == id);
        if (existing is null) return null;

        var items = NormaliseItems(draft.Items);

        existing.SupplierName = (draft.SupplierName ?? string.Empty).Trim();
        existing.SupplierContact = draft.SupplierContact?.Trim();
        existing.Status = DeriveStatus(items, draft.Status);
        existing.OrderDate = draft.OrderDate;
        existing.ExpectedDate = draft.ExpectedDate;
        existing.Notes = draft.Notes?.Trim();
        existing.UpdatedAt = DateTime.UtcNow.ToString("o");

        // Replace the line items wholesale (cascade delete removes the old rows).
        _db.PurchaseOrderItems.RemoveRange(existing.Items);
        existing.Items = items;

        await _db.SaveChangesAsync();
        return existing;
    }

    public async Task<bool> DeleteAsync(int id)
    {
        var existing = await _db.PurchaseOrders.FirstOrDefaultAsync(p => p.Id == id);
        if (existing is null) return false;

        _db.PurchaseOrders.Remove(existing);
        await _db.SaveChangesAsync();
        return true;
    }

    public async Task<PurchaseOrder?> ReceiveAsync(int id, List<ReceiptRequest> receipts)
    {
        var po = await _db.PurchaseOrders
            .Include(p => p.Items)
            .FirstOrDefaultAsync(p => p.Id == id);
        if (po is null) return null;

        var valid = (receipts ?? new List<ReceiptRequest>()).Where(r => r.Qty > 0).ToList();

        foreach (var item in po.Items)
        {
            var receipt = valid.FirstOrDefault(r => r.ItemId == item.Id);
            if (receipt is not null)
                item.ReceivedQty += receipt.Qty;
        }

        // A draft becomes "ordered" once it starts receiving, then derives further.
        var fallback = po.Status == "draft" ? "ordered" : po.Status;
        po.Status = DeriveStatus(po.Items.ToList(), fallback);
        po.UpdatedAt = DateTime.UtcNow.ToString("o");

        await _db.SaveChangesAsync();
        return po;
    }

    /// <summary>Generates the next sequential PO number, e.g. PO-2026-0004.</summary>
    private async Task<string> NextPoNoAsync()
    {
        var year = DateTime.UtcNow.Year;
        var prefix = $"PO-{year}-";

        var maxSeq = 0;
        var numbers = await _db.PurchaseOrders
            .Where(p => p.PoNo.StartsWith(prefix))
            .Select(p => p.PoNo)
            .ToListAsync();

        foreach (var no in numbers)
        {
            if (int.TryParse(no[prefix.Length..], out var seq))
                maxSeq = Math.Max(maxSeq, seq);
        }

        return $"{prefix}{(maxSeq + 1):D4}";
    }

    /// <summary>
    /// Derive status from received quantities (unless cancelled/draft). Mirrors
    /// the frontend deriveStatus().
    /// </summary>
    private static string DeriveStatus(List<PurchaseOrderItem> items, string? fallback)
    {
        fallback ??= "draft";
        if (fallback is "cancelled" or "draft") return fallback;

        var allReceived = items.Count > 0 && items.All(it => it.ReceivedQty >= it.Quantity);
        var anyReceived = items.Any(it => it.ReceivedQty > 0);
        if (allReceived) return "received";
        if (anyReceived) return "partially_received";
        return fallback;
    }

    /// <summary>
    /// Maps incoming request rows into entities: strings trimmed, empty rows
    /// dropped. Ids are left unset so the database auto-generates them.
    /// </summary>
    private static List<PurchaseOrderItem> NormaliseItems(List<PurchaseOrderItemRequest>? items)
    {
        items ??= new List<PurchaseOrderItemRequest>();
        return items
            .Where(i => !string.IsNullOrWhiteSpace(i.MaterialName))
            .Select(i => new PurchaseOrderItem
            {
                MaterialName = i.MaterialName.Trim(),
                MaterialCode = i.MaterialCode?.Trim(),
                RawMaterialId = i.RawMaterialId,
                Quantity = i.Quantity,
                Unit = string.IsNullOrWhiteSpace(i.Unit) ? "kg" : i.Unit,
                UnitPrice = i.UnitPrice,
                ReceivedQty = i.ReceivedQty,
            })
            .ToList();
    }
}
