using ERP_API.Data;
using ERP_API.Dtos;
using ERP_API.Interfaces;
using ERP_API.Models;
using Microsoft.EntityFrameworkCore;

namespace ERP_API.Services;

/// <summary>
/// EF Core-backed implementation of <see cref="IProductionService"/>. Mirrors the
/// frontend production.service.js: sequential work-order numbers (WO-2026-NNNN),
/// material normalisation, and the produce() loop-closer math.
/// </summary>
public class ProductionService : IProductionService
{
    private readonly ErpDbContext _db;

    public ProductionService(ErpDbContext db) => _db = db;

    public async Task<List<ProductionOrder>> GetAllAsync()
    {
        return await _db.ProductionOrders
            .Include(p => p.Materials)
            .OrderByDescending(p => p.CreatedAt)
            .ToListAsync();
    }

    public async Task<ProductionOrder?> GetByIdAsync(int id)
    {
        return await _db.ProductionOrders
            .Include(p => p.Materials)
            .FirstOrDefaultAsync(p => p.Id == id);
    }

    public async Task<ProductionOrder> CreateAsync(ProductionOrderRequest draft)
    {
        var now = DateTime.UtcNow.ToString("o");
        var record = new ProductionOrder
        {
            // Id is auto-generated by the database (auto-increment).
            WoNo = await NextWoNoAsync(),
            ProductName = (draft.ProductName ?? string.Empty).Trim(),
            ProductCode = draft.ProductCode?.Trim(),
            FinishedGoodId = draft.FinishedGoodId,
            Quantity = draft.Quantity,
            Unit = string.IsNullOrWhiteSpace(draft.Unit) ? "pcs" : draft.Unit,
            ProducedQty = 0,
            Status = string.IsNullOrWhiteSpace(draft.Status) ? "planned" : draft.Status,
            DueDate = draft.DueDate,
            SourceInquiryId = draft.SourceInquiryId,
            SourceInquiryNo = draft.SourceInquiryNo,
            Notes = draft.Notes?.Trim(),
            Materials = NormaliseMaterials(draft.Materials),
            CreatedBy = "Operations User",
            CreatedAt = now,
            UpdatedAt = now,
        };

        _db.ProductionOrders.Add(record);
        await _db.SaveChangesAsync();
        return record;
    }

    public async Task<ProductionOrder?> UpdateAsync(int id, ProductionOrderRequest draft)
    {
        var existing = await _db.ProductionOrders
            .Include(p => p.Materials)
            .FirstOrDefaultAsync(p => p.Id == id);
        if (existing is null) return null;

        existing.ProductName = (draft.ProductName ?? string.Empty).Trim();
        existing.ProductCode = draft.ProductCode?.Trim();
        existing.Quantity = draft.Quantity;
        existing.Unit = string.IsNullOrWhiteSpace(draft.Unit) ? "pcs" : draft.Unit;
        existing.Status = string.IsNullOrWhiteSpace(draft.Status) ? existing.Status : draft.Status;
        existing.DueDate = draft.DueDate;
        existing.Notes = draft.Notes?.Trim();
        existing.UpdatedAt = DateTime.UtcNow.ToString("o");

        // Replace materials wholesale (cascade delete removes the old rows).
        _db.WorkOrderMaterials.RemoveRange(existing.Materials);
        existing.Materials = NormaliseMaterials(draft.Materials);

        await _db.SaveChangesAsync();
        return existing;
    }

    public async Task<bool> DeleteAsync(int id)
    {
        var existing = await _db.ProductionOrders.FirstOrDefaultAsync(p => p.Id == id);
        if (existing is null) return false;

        _db.ProductionOrders.Remove(existing);
        await _db.SaveChangesAsync();
        return true;
    }

    public async Task<ProductionOrder?> ProduceAsync(int id, double qty)
    {
        var wo = await _db.ProductionOrders
            .Include(p => p.Materials)
            .FirstOrDefaultAsync(p => p.Id == id);
        if (wo is null) return null;

        var quantity = wo.Quantity;
        var outstanding = Math.Max(0, quantity - wo.ProducedQty);
        var make = Math.Min(qty, outstanding);
        if (make <= 0) return wo;   // nothing to do; return unchanged

        var fraction = quantity > 0 ? make / quantity : 0;

        // Advance each material's consumed quantity proportionally.
        foreach (var material in wo.Materials)
        {
            material.ConsumedQty = Round(material.ConsumedQty + material.Quantity * fraction);
        }

        wo.ProducedQty = Round(wo.ProducedQty + make);
        wo.Status = wo.ProducedQty >= quantity ? "completed" : "in_progress";
        wo.UpdatedAt = DateTime.UtcNow.ToString("o");

        await _db.SaveChangesAsync();
        return wo;
    }

    /// <summary>Generates the next sequential work-order number, e.g. WO-2026-0004.</summary>
    private async Task<string> NextWoNoAsync()
    {
        var year = DateTime.UtcNow.Year;
        var prefix = $"WO-{year}-";

        var maxSeq = 0;
        var numbers = await _db.ProductionOrders
            .Where(p => p.WoNo.StartsWith(prefix))
            .Select(p => p.WoNo)
            .ToListAsync();

        foreach (var no in numbers)
        {
            if (int.TryParse(no[prefix.Length..], out var seq))
                maxSeq = Math.Max(maxSeq, seq);
        }

        return $"{prefix}{(maxSeq + 1):D4}";
    }

    /// <summary>Round to 3 decimal places, matching the frontend round() helper.</summary>
    private static double Round(double value) => Math.Round(value * 1000) / 1000;

    /// <summary>
    /// Maps incoming request rows into entities: strings trimmed, empty rows
    /// dropped. Ids are left unset so the database auto-generates them.
    /// </summary>
    private static List<WorkOrderMaterial> NormaliseMaterials(List<WorkOrderMaterialRequest>? materials)
    {
        materials ??= new List<WorkOrderMaterialRequest>();
        return materials
            .Where(m => !string.IsNullOrWhiteSpace(m.MaterialName))
            .Select(m => new WorkOrderMaterial
            {
                MaterialName = m.MaterialName.Trim(),
                MaterialCode = m.MaterialCode?.Trim(),
                RawMaterialId = m.RawMaterialId,
                Quantity = m.Quantity,
                Unit = string.IsNullOrWhiteSpace(m.Unit) ? "kg" : m.Unit,
                ConsumedQty = m.ConsumedQty,
            })
            .ToList();
    }
}
