using ERP_API.Data;
using ERP_API.Dtos;
using ERP_API.Interfaces;
using ERP_API.Models;
using Microsoft.EntityFrameworkCore;

namespace ERP_API.Services;

/// <summary>
/// EF Core-backed implementation of <see cref="IQuotationService"/>. Mirrors the
/// frontend quotation.service.js: sequential quote numbers (QT-2026-NNNN), item
/// normalisation, and created/updated timestamps.
/// </summary>
public class QuotationService : IQuotationService
{
    private readonly ErpDbContext _db;

    public QuotationService(ErpDbContext db) => _db = db;

    public async Task<List<Quotation>> GetAllAsync()
    {
        return await _db.Quotations
            .Include(q => q.Items)
            .OrderByDescending(q => q.CreatedAt)
            .ToListAsync();
    }

    public async Task<Quotation?> GetByIdAsync(int id)
    {
        return await _db.Quotations
            .Include(q => q.Items)
            .FirstOrDefaultAsync(q => q.Id == id);
    }

    public async Task<Quotation> CreateAsync(QuotationRequest draft)
    {
        var now = DateTime.UtcNow.ToString("o");
        var record = new Quotation
        {
            // Id is auto-generated by the database (auto-increment).
            QuoteNo = await NextQuoteNoAsync(),
            CustomerName = (draft.CustomerName ?? string.Empty).Trim(),
            CustomerContact = draft.CustomerContact?.Trim(),
            SourceInquiryId = draft.SourceInquiryId,
            SourceInquiryNo = draft.SourceInquiryNo,
            QuoteDate = draft.QuoteDate,
            ValidUntil = draft.ValidUntil,
            Status = string.IsNullOrWhiteSpace(draft.Status) ? "draft" : draft.Status,
            Notes = draft.Notes?.Trim(),
            Items = NormaliseItems(draft.Items),
            CreatedBy = "Operations User",
            CreatedAt = now,
            UpdatedAt = now,
        };

        _db.Quotations.Add(record);
        await _db.SaveChangesAsync();
        return record;
    }

    public async Task<Quotation?> UpdateAsync(int id, QuotationRequest draft)
    {
        var existing = await _db.Quotations
            .Include(q => q.Items)
            .FirstOrDefaultAsync(q => q.Id == id);
        if (existing is null) return null;

        existing.CustomerName = (draft.CustomerName ?? string.Empty).Trim();
        existing.CustomerContact = draft.CustomerContact?.Trim();
        existing.SourceInquiryId = draft.SourceInquiryId;
        existing.SourceInquiryNo = draft.SourceInquiryNo;
        existing.QuoteDate = draft.QuoteDate;
        existing.ValidUntil = draft.ValidUntil;
        existing.Status = string.IsNullOrWhiteSpace(draft.Status) ? existing.Status : draft.Status;
        existing.Notes = draft.Notes?.Trim();
        existing.UpdatedAt = DateTime.UtcNow.ToString("o");

        // Replace the line items wholesale (cascade delete removes the old rows).
        _db.QuotationItems.RemoveRange(existing.Items);
        existing.Items = NormaliseItems(draft.Items);

        await _db.SaveChangesAsync();
        return existing;
    }

    public async Task<bool> DeleteAsync(int id)
    {
        var existing = await _db.Quotations.FirstOrDefaultAsync(q => q.Id == id);
        if (existing is null) return false;

        _db.Quotations.Remove(existing);
        await _db.SaveChangesAsync();
        return true;
    }

    public async Task<Quotation?> SetStatusAsync(int id, string status)
    {
        var existing = await _db.Quotations.FirstOrDefaultAsync(q => q.Id == id);
        if (existing is null) return null;

        existing.Status = status;
        existing.UpdatedAt = DateTime.UtcNow.ToString("o");
        await _db.SaveChangesAsync();
        return existing;
    }

    /// <summary>Generates the next sequential quote number, e.g. QT-2026-0004.</summary>
    private async Task<string> NextQuoteNoAsync()
    {
        var year = DateTime.UtcNow.Year;
        var prefix = $"QT-{year}-";

        var maxSeq = 0;
        var numbers = await _db.Quotations
            .Where(q => q.QuoteNo.StartsWith(prefix))
            .Select(q => q.QuoteNo)
            .ToListAsync();

        foreach (var no in numbers)
        {
            if (int.TryParse(no[prefix.Length..], out var seq))
                maxSeq = Math.Max(maxSeq, seq);
        }

        return $"{prefix}{(maxSeq + 1):D4}";
    }

    /// <summary>
    /// Maps incoming request rows into entities: strings trimmed, empty rows
    /// dropped. Ids are left unset so the database auto-generates them.
    /// </summary>
    private static List<QuotationItem> NormaliseItems(List<QuotationItemRequest>? items)
    {
        items ??= new List<QuotationItemRequest>();
        return items
            .Where(i => !string.IsNullOrWhiteSpace(i.ProductName))
            .Select(i => new QuotationItem
            {
                ProductName = i.ProductName.Trim(),
                ProductCode = i.ProductCode?.Trim(),
                Quantity = i.Quantity,
                Unit = string.IsNullOrWhiteSpace(i.Unit) ? "pcs" : i.Unit,
                DeliveryDate = i.DeliveryDate,
                UnitPrice = i.UnitPrice,
            })
            .ToList();
    }
}
