using ERP_API.Data;
using ERP_API.Dtos;
using ERP_API.Interfaces;
using ERP_API.Models;
using Microsoft.EntityFrameworkCore;

namespace ERP_API.Services;

/// <summary>
/// EF Core-backed implementation of <see cref="ISalesOrderService"/>. Mirrors the
/// frontend sales.service.js: sequential order numbers (SO-2026-NNNN), item
/// normalisation, created/updated timestamps. New orders default to "confirmed".
/// </summary>
public class SalesOrderService : ISalesOrderService
{
    private readonly ErpDbContext _db;

    public SalesOrderService(ErpDbContext db) => _db = db;

    public async Task<List<SalesOrder>> GetAllAsync()
    {
        return await _db.SalesOrders
            .Include(s => s.Items)
            .OrderByDescending(s => s.CreatedAt)
            .ToListAsync();
    }

    public async Task<SalesOrder?> GetByIdAsync(int id)
    {
        return await _db.SalesOrders
            .Include(s => s.Items)
            .FirstOrDefaultAsync(s => s.Id == id);
    }

    public async Task<SalesOrder> CreateAsync(SalesOrderRequest draft)
    {
        var now = DateTime.UtcNow.ToString("o");
        var record = new SalesOrder
        {
            // Id is auto-generated by the database (auto-increment).
            SoNo = await NextSoNoAsync(),
            CustomerName = (draft.CustomerName ?? string.Empty).Trim(),
            CustomerContact = draft.CustomerContact?.Trim(),
            SourceInquiryId = draft.SourceInquiryId,
            SourceInquiryNo = draft.SourceInquiryNo,
            OrderDate = draft.OrderDate,
            ExpectedDeliveryDate = draft.ExpectedDeliveryDate,
            Status = string.IsNullOrWhiteSpace(draft.Status) ? "confirmed" : draft.Status,
            Notes = draft.Notes?.Trim(),
            Items = NormaliseItems(draft.Items),
            CreatedBy = "Operations User",
            CreatedAt = now,
            UpdatedAt = now,
        };

        _db.SalesOrders.Add(record);
        await _db.SaveChangesAsync();
        return record;
    }

    public async Task<SalesOrder?> UpdateAsync(int id, SalesOrderRequest draft)
    {
        var existing = await _db.SalesOrders
            .Include(s => s.Items)
            .FirstOrDefaultAsync(s => s.Id == id);
        if (existing is null) return null;

        existing.CustomerName = (draft.CustomerName ?? string.Empty).Trim();
        existing.CustomerContact = draft.CustomerContact?.Trim();
        existing.SourceInquiryId = draft.SourceInquiryId;
        existing.SourceInquiryNo = draft.SourceInquiryNo;
        existing.OrderDate = draft.OrderDate;
        existing.ExpectedDeliveryDate = draft.ExpectedDeliveryDate;
        existing.Status = string.IsNullOrWhiteSpace(draft.Status) ? existing.Status : draft.Status;
        existing.Notes = draft.Notes?.Trim();
        existing.UpdatedAt = DateTime.UtcNow.ToString("o");

        // Replace the line items wholesale (cascade delete removes the old rows).
        _db.SalesOrderItems.RemoveRange(existing.Items);
        existing.Items = NormaliseItems(draft.Items);

        await _db.SaveChangesAsync();
        return existing;
    }

    public async Task<bool> DeleteAsync(int id)
    {
        var existing = await _db.SalesOrders.FirstOrDefaultAsync(s => s.Id == id);
        if (existing is null) return false;

        _db.SalesOrders.Remove(existing);
        await _db.SaveChangesAsync();
        return true;
    }

    public async Task<SalesOrder?> SetStatusAsync(int id, string status)
    {
        var existing = await _db.SalesOrders.FirstOrDefaultAsync(s => s.Id == id);
        if (existing is null) return null;

        existing.Status = status;
        existing.UpdatedAt = DateTime.UtcNow.ToString("o");
        await _db.SaveChangesAsync();
        return existing;
    }

    /// <summary>Generates the next sequential order number, e.g. SO-2026-0004.</summary>
    private async Task<string> NextSoNoAsync()
    {
        var year = DateTime.UtcNow.Year;
        var prefix = $"SO-{year}-";

        var maxSeq = 0;
        var numbers = await _db.SalesOrders
            .Where(s => s.SoNo.StartsWith(prefix))
            .Select(s => s.SoNo)
            .ToListAsync();

        foreach (var no in numbers)
        {
            if (int.TryParse(no[prefix.Length..], out var seq))
                maxSeq = Math.Max(maxSeq, seq);
        }

        return $"{prefix}{(maxSeq + 1):D4}";
    }

    /// <summary>
    /// Maps incoming request rows into entities: strings trimmed, empty rows
    /// dropped. Ids are left unset so the database auto-generates them.
    /// </summary>
    private static List<SalesOrderItem> NormaliseItems(List<SalesOrderItemRequest>? items)
    {
        items ??= new List<SalesOrderItemRequest>();
        return items
            .Where(i => !string.IsNullOrWhiteSpace(i.ProductName))
            .Select(i => new SalesOrderItem
            {
                ProductName = i.ProductName.Trim(),
                ProductCode = i.ProductCode?.Trim(),
                Quantity = i.Quantity,
                Unit = string.IsNullOrWhiteSpace(i.Unit) ? "pcs" : i.Unit,
                DeliveryDate = i.DeliveryDate,
                UnitPrice = i.UnitPrice,
            })
            .ToList();
    }
}
